[package]
name = "transposer2025"
version = "1.0.0"
edition = "2021"

[dependencies]
midir = "0.10.2"
rosc = "0.11.4"
rumqttc = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
winres = "0.1.12"
