name: Bump Major Version

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    bump-major:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Make bump script executable
              run: chmod +x .github/scripts/bump_major.sh

            - name: Run bump_major
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  .github/scripts/bump_major.sh
